repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # General file hygiene checks (fast and prevent unnecessary processing)
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

      # Basic repository checks
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

      # Syntax and formatting validations
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml

      # Code quality and security checks
      - id: check-docstring-first
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      # Code modernization
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      # Import sorting
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      # Linting and formatting
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.0"
    hooks:
      # Security analysis
      - id: bandit

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.18
    hooks:
      # Custom lock file management
      - id: uv-lock
